# Importing Library Package TFIDF

In [0]:
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Masukin data perparagraf

In [0]:
datatext = []

In [0]:
datatext.append('''Catteleya Walkerina. Found in Goias, Minas Gerais, Espirito Santo and Sao Paulo states of Brazil on giant old trees on rocky limestone plateaus or small trees or moist rocks near streams at elevations up to 2000 meters with jointed, bulbous or shortly fusiform, shiny yellow pseudobulbs carrying a single [rarely 2], apical, elliptic or ovate, leathery leaf that is rounded apically and blooms mostly in the fall but can occur at other times [see varieties below] on a 3" [7.5 cm] long, arcuate, single to few [1 to 3] flowered inflorescence carrying fragrant vanilla to cinnamon scented flowers that open very flat. This species and C. nobilor are the only Cattleya that the terminal, shorter, 1 to few flowered inflorescence arises from the base of the pseudobulb seemingly as a new growth.''')
datatext.append('''Ruby Lipped Cattleya. Found in Venezuela and Maranhao, Piaui, Ceara, Pernambuco and Alagoas states of Brazil at elevations of 600 to 900 meters as a warm growing, variable sized epiphyte with club-shaped, slightly compressed pseudobulbs subtended by several greenish, thin textured sheaths and carrying a single, apical, oblong, obtuse, coriaceous leaf that blooms mostly in the fall and early winter on a short, few [2 to 5] flowered inflorescence subtended by a double, leathery sheath and carrying spicy, aromatic to clove scented flowers.''')
datatext.append('''Cattleya maxima. A medium sized, cool to warm growing, unifoliate, epiphyte and occasional lithophyte from Venezuela, Colombia, Ecuador and northern coastal Peru that is found at elevations of 10 to 1500 meters in seasonally dry, coastal forests with clavate, lightly complante, sulcate pseudobulbs subtended by several, imbricating, nonfoliaceous sheaths and a single, apical, oblong or narrowly elliptic-oblong, clasping, obtuse, minutely bilobed, thickly coriaceous leaf and blooms in the fall through the winter on a terminal, to 12" [30 cm] long, erect or arching, few to several flowered, racemose inflorescence arising on a mature pseudobulb subtended with a large, basal, elongate sheath from which arise 3 to 15, long-lived, fragrant helioptrope to sweet pea scented, somewhat heavy textured flowers that are held just at or above leaf height.''')
datatext.append('''Intermedia Cattleya. Found in Sao Paulo, Santa Catarina and Rio Grande do Sul states of Brazil, Uruguay and Argentina in the Atlantic coastal forest on rocks and small trees near the sea or streams as a small to medium sized, cool to warm growing orchid with slender, cylindric pseudobulbs with several, tubular, scarious bracts enveloping it and 2 to 4, apical, subopposite leaves that blooms in the spring or summer on a terminal, short to long stalked, few to several [3 to 7] flowered inflorecence with minute floral bracts and subtended by a conduplicate sheath all arising on a newly matured pseudobulb with heavy textured, long-lived, fragrant floral scented , color variable flowers. The in situ shots are from Boia Ceia', Sao Paulo State, Brasil. These plants are plentiful in their specific environment which encompasses the exact area that condos by the sea are most often built. The sea gives way to the sand and then the sand gives way to vines and grasses and then to small bushes and then begins the hammock of stunted hardwoods with swales of tidal saltwater and freshwater runnoff. This area is extremely humid and hot and is bathed by spray from the crashing surf less than 20 yards away. Cattleya intermedia is found in these hammocks in vast quanities. I saw close to 500 just in a 30 acre area. Almost all were on trees at or just above eye-level. The branches and trunks were extremely damp and had lichen and mosses. There was a lot of standing water with mosquitoes and bromeliads were everywhere. All discussions about this species being extinct or rare in the wild are hogwash and it is not threatened by over-collection as stated by Bechtel-Cribb in the Manual of Cultivated Orchids.''')
datatext.append('''The Noble Cattleya. Found in Matto Grossa, DF and Goias State of Brazil as well as Santa Cruz Bolivia and Paraguay along rivers on roughbarked trees at the edges of high cliffs in full sun and with ample air circulation at elevations of 170 to 700 meters as a small to medium sized, hot to warm growing epiphyte. This species is characterized by having ellipsoid pseudobulbs carrying 2 apical, elliptic to elliptic-oblong, coriaceous leaves and blooms on a to 3 1/8" [to 8 cm] long, slender, 1 to few flowered inflorescence with up to 5 extremely [vanilla citron] fragrant flowers. This species is always bifoliate and can be distinguished from Cattleya walkeriana by this fact alone as C walkeriana has only one. This area has a distinct wet and dry period and it is quite hot. A five month drier rest from November through March is reccomended. The var amaliae pictured above is cooler growing and comes from the Brazilian states of Goias and Tocantins at elevations to 900 meters on rough barked trees.''')

In [0]:
datatext

['Catteleya Walkerina. Found in Goias, Minas Gerais, Espirito Santo and Sao Paulo states of Brazil on giant old trees on rocky limestone plateaus or small trees or moist rocks near streams at elevations up to 2000 meters with jointed, bulbous or shortly fusiform, shiny yellow pseudobulbs carrying a single [rarely 2], apical, elliptic or ovate, leathery leaf that is rounded apically and blooms mostly in the fall but can occur at other times [see varieties below] on a 3" [7.5 cm] long, arcuate, single to few [1 to 3] flowered inflorescence carrying fragrant vanilla to cinnamon scented flowers that open very flat. This species and C. nobilor are the only Cattleya that the terminal, shorter, 1 to few flowered inflorescence arises from the base of the pseudobulb seemingly as a new growth.',
 'Ruby Lipped Cattleya. Found in Venezuela and Maranhao, Piaui, Ceara, Pernambuco and Alagoas states of Brazil at elevations of 600 to 900 meters as a warm growing, variable sized epiphyte with club-shaped, slightly compressed pseudobulbs subtended by several greenish, thin textured sheaths and carrying a single, apical, oblong, obtuse, coriaceous leaf that blooms mostly in the fall and early winter on a short, few [2 to 5] flowered inflorescence subtended by a double, leathery sheath and carrying spicy, aromatic to clove scented flowers.',
 'Cattleya maxima. A medium sized, cool to warm growing, unifoliate, epiphyte and occasional lithophyte from Venezuela, Colombia, Ecuador and northern coastal Peru that is found at elevations of 10 to 1500 meters in seasonally dry, coastal forests with clavate, lightly complante, sulcate pseudobulbs subtended by several, imbricating, nonfoliaceous sheaths and a single, apical, oblong or narrowly elliptic-oblong, clasping, obtuse, minutely bilobed, thickly coriaceous leaf and blooms in the fall through the winter on a terminal, to 12" [30 cm] long, erect or arching, few to several flowered, racemose inflorescence arising on a mature pseudobulb subtended with a large, basal, elongate sheath from which arise 3 to 15, long-lived, fragrant helioptrope to sweet pea scented, somewhat heavy textured flowers that are held just at or above leaf height.',
 "Intermedia Cattleya. Found in Sao Paulo, Santa Catarina and Rio Grande do Sul states of Brazil, Uruguay and Argentina in the Atlantic coastal forest on rocks and small trees near the sea or streams as a small to medium sized, cool to warm growing orchid with slender, cylindric pseudobulbs with several, tubular, scarious bracts enveloping it and 2 to 4, apical, subopposite leaves that blooms in the spring or summer on a terminal, short to long stalked, few to several [3 to 7] flowered inflorecence with minute floral bracts and subtended by a conduplicate sheath all arising on a newly matured pseudobulb with heavy textured, long-lived, fragrant floral scented , color variable flowers. The in situ shots are from Boia Ceia', Sao Paulo State, Brasil. These plants are plentiful in their specific environment which encompasses the exact area that condos by the sea are most often built. The sea gives way to the sand and then the sand gives way to vines and grasses and then to small bushes and then begins the hammock of stunted hardwoods with swales of tidal saltwater and freshwater runnoff. This area is extremely humid and hot and is bathed by spray from the crashing surf less than 20 yards away. Cattleya intermedia is found in these hammocks in vast quanities. I saw close to 500 just in a 30 acre area. Almost all were on trees at or just above eye-level. The branches and trunks were extremely damp and had lichen and mosses. There was a lot of standing water with mosquitoes and bromeliads were everywhere. All discussions about this species being extinct or rare in the wild are hogwash and it is not threatened by over-collection as stated by Bechtel-Cribb in the Manual of Cultivated Orchids.",
 'The Noble Cattleya. Found in Matto Grossa, DF and Goias State of Brazil as well as Santa Cruz Bolivia and Paraguay along rivers on roughbarked trees at the edges of high cliffs in full sun and with ample air circulation at elevations of 170 to 700 meters as a small to medium sized, hot to warm growing epiphyte. This species is characterized by having ellipsoid pseudobulbs carrying 2 apical, elliptic to elliptic-oblong, coriaceous leaves and blooms on a to 3 1/8" [to 8 cm] long, slender, 1 to few flowered inflorescence with up to 5 extremely [vanilla citron] fragrant flowers. This species is always bifoliate and can be distinguished from Cattleya walkeriana by this fact alone as C walkeriana has only one. This area has a distinct wet and dry period and it is quite hot. A five month drier rest from November through March is reccomended. The var amaliae pictured above is cooler growing and comes from the Brazilian states of Goias and Tocantins at elevations to 900 meters on rough barked trees.']

# Hitung TFIDF

In [0]:
# calculate TFIDF using lib
# tf = n/sigma(n)
# idf = log(n/dft)
# tfidf = tf*idf

vect = TfidfVectorizer()
tfidf_matrix = vect.fit_transform(datatext)
tabel = pd.DataFrame(tfidf_matrix.toarray(), columns = vect.get_feature_names())

In [0]:
tabel.index.name = 'paragraf_ke'

In [0]:
tabel

                   10        12        15  ...      with     yards    yellow
paragraf_ke                                ...
0            0.000000  0.000000  0.000000  ...  0.048703  0.000000  0.102208
1            0.000000  0.000000  0.000000  ...  0.067724  0.000000  0.000000
2            0.103984  0.103984  0.103984  ...  0.099098  0.000000  0.000000
3            0.000000  0.000000  0.000000  ...  0.139334  0.048735  0.000000
4            0.000000  0.000000  0.000000  ...  0.073949  0.000000  0.000000

[5 rows x 360 columns]

In [0]:
tabel.reset_index()[['paragraf_ke', 'pseudobulbs']].rename(columns={"pseudobulbs": "nilai_tfidf_pseudobulbs"})

   paragraf_ke  nilai_tfidf_pseudobulbs
0            0                 0.048703
1            1                 0.067724
2            2                 0.049549
3            3                 0.023222
4            4                 0.036974

In [0]:
tabel.reset_index()[['paragraf_ke', 'aromatic']].rename(columns={"aromatic": "nilai_tfidf_aromatic"})

   paragraf_ke  nilai_tfidf_aromatic
0            0              0.000000
1            1              0.142127
2            2              0.000000
3            3              0.000000
4            4              0.000000